CREATE TABLE SALESPERSON(
SALESPERSON_ID SERIAL PRIMARY KEY,
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
PHONE CHAR(12),
EMAIL VARCHAR(150)
);

--MECHANIC TABLE
CREATE TABLE MECHANIC(
MECH_ID SERIAL PRIMARY KEY,
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
PHONE CHAR(12)
);
--PART TABLE
CREATE TABLE PARTS(
PART_ID SERIAL PRIMARY KEY,
PART_NAME VARCHAR(100),
SELLING_PRICE NUMERIC(10,2)
);

--CUSTOMER TABLE
CREATE TABLE CUSTOMER(
CUSTOMER_ID SERIAL PRIMARY KEY,
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
PHONE CHAR(12),
EMAIL VARCHAR(200)
);

--CARS TABLE
CREATE TABLE CARS(
CAR_ID SERIAL PRIMARY KEY,
MODEL VARCHAR(100),
MAKE VARCHAR(100),
YEAR INTEGER,
SALESPERSON_ID INTEGER,
CUSTOMER_ID INTEGER,
SELLING_PRICE NUMERIC(12,2),
FOREIGN KEY (SALESPERSON_ID) REFERENCES SALESPERSON(SALESPERSON_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

--INVOICE TABLE
CREATE TABLE INVOICE(
INVOICE_ID SERIAL PRIMARY KEY,
SALESPERSON_ID INTEGER,
CUSTOMER_ID INTEGER,
CAR_ID INTEGER,
DATE DATE,
TOTAL_COST NUMERIC(12,2),
FOREIGN KEY (SALESPERSON_ID) REFERENCES SALESPERSON(SALESPERSON_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID)
);

-- SERVICE TYPE TABLE
CREATE TABLE JOB(
JOB_ID SERIAL PRIMARY KEY,
DESCRIPTION VARCHAR(300),
HOURS  FLOAT,
MECH_ID INTEGER,
PART_ID INTEGER,
FOREIGN KEY (MECH_ID) REFERENCES MECHANIC(MECH_ID),
FOREIGN KEY (PART_ID) REFERENCES PARTS(PART_ID)
);
--SERVICE TABLE
CREATE TABLE SERVICE_LOG(
SERVICE_ID SERIAL PRIMARY KEY,
DATE TIMESTAMP,
COST NUMERIC(12,2),
CAR_ID INTEGER,
MECH_ID INTEGER,
PART_ID INTEGER,
FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID),
FOREIGN KEY (MECH_ID) REFERENCES MECHANIC(MECH_ID),
FOREIGN KEY (PART_ID) REFERENCES PARTS(PART_ID)
);
--TICKET
CREATE TABLE TICKET(
TICKET_ID SERIAL PRIMARY KEY,
DATE TIMESTAMP,
ISSUE VARCHAR(300),
CUSTOMER_ID INTEGER,
CAR_ID INTEGER,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID)
);

-- SERVICE HISTORY TABLE
CREATE TABLE HISTORY(
ISSUE_ID SERIAL PRIMARY KEY,
CAR_ID INTEGER,
TICKET_ID INTEGER,
FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID),
FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID)
);
