
--CREATING TABLES FOR MOVIE THEATRE DB
-- LANGUAGE TABLE
CREATE TABLE LANGUAGE(
LANGUAGE_ID SERIAL PRIMARY KEY,
LANGUAGE_NAME VARCHAR(50)
);

--MOVIE TABLE CREATION
CREATE TABLE MOVIE(
MOVIE_ID SERIAL PRIMARY KEY,
TITLE VARCHAR(150),
DIRECTOR VARCHAR(150),
GENRE VARCHAR(150),
LANGUAGE_ID INT,
RELEASE_YEAR INT,
LENGTH TIME,
RATING VARCHAR(50),
FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE(LANGUAGE_ID)
);

--STAFF TABLE
CREATE TABLE STAFF(
STAFF_ID SERIAL PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
POSITION VARCHAR(50),
HIRE_DATE DATE,
SALARY DECIMAL(8, 2)
);
--CUSTOMER TABLE CREATION
CREATE TABLE CUSTOMER(
CUSTOMER_ID SERIAL PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(50),
PHONE NUMERIC(12,0)
);

--TICKET TABLE
CREATE TABLE TICKET(
TICKET_ID SERIAL PRIMARY KEY,
STAFF_ID INTEGER,
MOVIE_ID INTEGER,
CUSTOMER_ID INTEGER,
PURCHARE_TIME TIMESTAMP,
SEAT_NUMBER INTEGER CHECK(SEAT_NUMBER BETWEEN 1 AND 200),
FOREIGN KEY(STAFF_ID) REFERENCES STAFF(STAFF_ID),
FOREIGN KEY(MOVIE_ID) REFERENCES MOVIE(MOVIE_ID),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);


--CONCESSION TABLE CREATION
CREATE TABLE CONCESSION(
CONCESSION_ID SERIAL PRIMARY KEY,
ITEM_NAME VARCHAR(100),
AMOUNT NUMERIC(10,2)
);

--SALES TABLE CREATION
CREATE TABLE SALES(
SALE_ID SERIAL PRIMARY KEY,
CONCESSION_ID INTEGER,
CUSTOMER_ID INTEGER,
TICKET_ID INTEGER,
SALE_TIME TIMESTAMP,
PAYMENT_ID INTEGER,
AMOUNT NUMERIC(5,2),
FOREIGN KEY (CONCESSION_ID) REFERENCES CONCESSION(CONCESSION_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID)
);

--INVENTORY TABLE CREATION
CREATE TABLE INVENTORY(
UPC SERIAL PRIMARY KEY,
CONCESSION_ID INTEGER,
QUANTITY_IN_STOCK INTEGER,
FOREIGN KEY (CONCESSION_ID) REFERENCES CONCESSION(CONCESSION_ID)
);
